---
- name: Load DockerHub token
  command: "echo $DOCKERHUB_TOKEN"
  register: dockerhub_token_output
  failed_when: dockerhub_token_output.stdout == ""
  changed_when: false

- name: Log in to DockerHub
  community.docker.docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_token_output.stdout }}"
  register: login_result