- name: Uninstall Kubernetes and restore system settings
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Check if Kubernetes is installed
      command: which kubeadm
      register: kubeadm_installed
      ignore_errors: yes
      changed_when: false

    - name: Drain and delete the node (if applicable)
      command: kubeadm reset -f
      when: kubeadm_installed.rc == 0

    - name: Uninstall Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: absent
      when: kubeadm_installed.rc == 0

    - name: Remove containerd
      apt:
        name: containerd
        state: absent

    - name: Remove Kubernetes configuration files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /var/lib/etcd
        - /var/lib/kubeadm
        - /etc/systemd/system/kubelet.service.d

    - name: Unload kernel modules
      shell: |
        modprobe -r overlay
        modprobe -r br_netfilter
      ignore_errors: yes

    - name: Remove kernel module configuration
      file:
        path: /etc/modules-load.d/containerd.conf
        state: absent

    - name: Remove sysctl settings
      file:
        path: /etc/sysctl.d/kubernetes.conf
        state: absent

    - name: Reload sysctl settings
      command: sysctl --system

    - name: Restore swap if previously disabled
      lineinfile:
        path: /etc/fstab
        regexp: '^#(.*\sswap\s.*)$'
        line: '\1'
        backrefs: yes

    - name: Re-enable swap
      command: swapon -a
      ignore_errors: yes

    - name: Remove Kubernetes package repository
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent

    - name: Remove Kubernetes GPG key
      file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: absent

    - name: Update package lists
      apt:
        update_cache: yes
