apiVersion: v1
kind: Secret
metadata:
  name: postgres-savannah-secret
type: Opaque
data:
  postgresqlUsername: {{ .Values.secrets.postgresqlUsername | b64enc }}
  postgresqlPassword: {{ .Values.secrets.postgresqlPassword | b64enc }}
