apiVersion: v1
kind: Secret
metadata:
  name: orders-service-secret
type: Opaque
data:
  DJANGO_POSTGRESQL_USERNAME: {{ .Values.secrets.DJANGO_POSTGRESQL_USERNAME | b64enc }}
  DJANGO_POSTGRESQL_PASSWORD: {{ .Values.secrets.DJANGO_POSTGRESQL_PASSWORD | b64enc }}
  CLIENT_ID: {{ .Values.secrets.CLIENT_ID | b64enc }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc }}
  CLIENT_SECRET: {{ .Values.secrets.CLIENT_SECRET | b64enc }}
