---
- name: Create logging directory
  file:
    path: "{{ log_dir }}"
    state: directory
    mode: "0755"

- name: Check minimum system requirements
  assert:
    that:
      - ansible_memtotal_mb >= 2048
      - ansible_processor_cores >= 1
    msg: "Minimum system requirements not met. Need 2GB RAM and 2 CPU cores"
  register: system_check
  # failed_when: not system_check.failed

- name: Check Ubuntu version
  assert:
    that: ansible_distribution_version is version('22.04', '>=')
    msg: "Ubuntu 22.04 or higher is required"

- name: Check required ports availability
  wait_for:
    port: "{{ item }}"
    state: stopped
    timeout: 10
  loop:
    - 6443 # Kubernetes API server
    - 2379 # etcd
    - 2380 # etcd peer
    - 10250 # Kubelet API
  register: ports_check
